### PR TITLE
port to python 38

### PR DESCRIPTION
**Pull request by bissenbay**
Related-To: https://github.com/thoth-station/thoth-application/issues/545

### CODE REVIEW

**Comment by harshad16** [comment]
can you please include the `.aicoe-ci.yaml`
```
check:
  - thoth-build
build:
  base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
  build-stratergy: Source
  registry: quay.io
  registry-org: thoth-station
  registry-project: metrics-exporter
  registry-secret: thoth-station-thoth-pusher-secret
deploy:
  project-org: "thoth-station"
  project-name: "thoth-application"
  image-name: "metrics-exporter"
  overlay-contextpath: "metrics-exporter/overlays/test/imagestreamtag.yaml"
```

**Comment by bissenbay** [comment]
> can you please include the `.aicoe-ci.yaml`
> 
> ```
> check:
>   - thoth-build
> build:
>   base-image: quay.io/thoth-station/s2i-thoth-ubi8-py38:latest
>   build-stratergy: Source
>   registry: quay.io
>   registry-org: thoth-station
>   registry-project: metrics-exporter
>   registry-secret: thoth-station-thoth-pusher-secret
> deploy:
>   project-org: "thoth-station"
>   project-name: "thoth-application"
>   image-name: "metrics-exporter"
>   overlay-contextpath: "metrics-exporter/overlays/test/imagestreamtag.yaml"
> ```

thanks @harshad16 , https://github.com/thoth-station/metrics-exporter/pull/548/commits/48fa6fbf4684fe2b04102aeb2b751bd1cafac792

**Comment by bissenbay** [comment]
@harshad16 made changes here as well

**Comment by bissenbay** [comment]
@fridex @harshad16 PTAL

**Review by harshad16 — APPROVED** [review]
lgtm, thanks :100:

**Review by fridex — APPROVED** [review]
:100: :ship:

**Pull request merged**
