### PR TITLE
Add check on number of solvers from CM and from database

### PR DESCRIPTION
**Pull request by pacospace**
Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

## Related Issues and Dependencies

Related-To: https://github.com/thoth-station/metrics-exporter/issues/586

## This introduces a breaking change

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
the alarm can wait till the next sprint cycle.

**Review by fridex — APPROVED** [review]
lgtm :+1: :100:

**Comment by pacospace** [comment]
> /lgtm
> the alarm can wait till the next sprint cycle.

Sure!! I will just have it in test :)

**Comment by pacospace** [comment]
> /lgtm
> the alarm can wait till the next sprint cycle.

https://github.com/orgs/thoth-station/projects/18 I create new project to track what we want for next @goern @fridex @KPostOffice @harshad16

**Pull request merged**
