### PR TITLE
Update GitHub templates and pre-commit plugin versions

### PR DESCRIPTION
**Pull request by codificat**
## This Pull Request implements

Update the GitHub issue templates using the ones from the template project.

## Description

The main need here was to switch the default issue label to `needs-triage` instead of `triage/needs-information` (the latter is to be added after a review that detects missing information), and the removal of the Yes/No check-box style from #840.

Also taking the opportunity to update pre-commit plugins

### CODE REVIEW

**Review by harshad16 — APPROVED** [review]
lgtm
thanks :100:

**Comment by codificat** [comment]
/assign @fridex 
for approval, thanks

**Pull request merged**
