### PR TITLE
Created metrics for PI

### PR DESCRIPTION
**Pull request by pacospace**
Depends-On: https://github.com/thoth-station/storages/pull/852#issuecomment-516428234

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

### CODE REVIEW

**Comment by pacospace** [comment]
recheck

**Comment by fridex** [comment]
recheck

**Comment by pacospace** [comment]
> Build failed.
> 
> * [thoth-coala ](thoth-coala) : NODE_FAILURE in 0s

Why a failure here?

**Comment by fridex** [comment]
> > Build failed.
> > 
> > * [thoth-coala ](thoth-coala) : NODE_FAILURE in 0s
> 
> Why a failure here?

:snowflake:

**Pull request merged**
